"""add_visitor_id_to_analytics

Revision ID: 8ffbaf51245b
Revises: 790b25c42127
Create Date: 2026-04-17 16:23:42.624592
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '8ffbaf51245b'
down_revision: Union[str, None] = '790b25c42127'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_events', sa.Column('visitor_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_site_events_visitor_id'), 'site_events', ['visitor_id'], unique=False)
    op.add_column('site_page_views', sa.Column('visitor_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_site_page_views_visitor_id'), 'site_page_views', ['visitor_id'], unique=False)
    op.add_column('site_search_logs', sa.Column('visitor_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_site_search_logs_visitor_id'), 'site_search_logs', ['visitor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_site_search_logs_visitor_id'), table_name='site_search_logs')
    op.drop_column('site_search_logs', 'visitor_id')
    op.drop_index(op.f('ix_site_page_views_visitor_id'), table_name='site_page_views')
    op.drop_column('site_page_views', 'visitor_id')
    op.drop_index(op.f('ix_site_events_visitor_id'), table_name='site_events')
    op.drop_column('site_events', 'visitor_id')
    # ### end Alembic commands ###
