"""add_nickname_to_users

Revision ID: 9a262f8f6683
Revises: 2becc64be0cb
Create Date: 2026-04-10 08:13:18.914898
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '9a262f8f6683'
down_revision: Union[str, None] = '2becc64be0cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nickname', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'nickname')
    # ### end Alembic commands ###
