"""Initial schema

Revision ID: b3b50b1115a9
Revises: 
Create Date: 2026-03-19 09:30:26.600272
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b3b50b1115a9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SEQUENCE IF NOT EXISTS patients_display_id_seq")
    op.execute("CREATE SEQUENCE IF NOT EXISTS visits_display_id_seq")
    op.execute("CREATE SEQUENCE IF NOT EXISTS summaries_display_id_seq")

    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_type'), 'audit_log', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_table('clinics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=False),
    sa.Column('tag_type', sa.String(length=50), nullable=False),
    sa.Column('tag_code', sa.String(length=50), nullable=True),
    sa.Column('tag_label', sa.String(length=255), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=20), server_default='manual', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_entity_id'), 'tags', ['entity_id'], unique=False)
    op.create_index(op.f('ix_tags_entity_type'), 'tags', ['entity_type'], unique=False)
    op.create_index(op.f('ix_tags_source'), 'tags', ['source'], unique=False)
    op.create_index(op.f('ix_tags_tag_code'), 'tags', ['tag_code'], unique=False)
    op.create_index(op.f('ix_tags_tag_type'), 'tags', ['tag_type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('auth_method', sa.String(length=20), server_default='google', nullable=False),
    sa.Column('role', sa.Enum('doctor', 'admin', 'receptionist', name='userrole'), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('patient_key_type', sa.Enum('national_id', 'phone', 'email', name='patientkeytype'), server_default='national_id', nullable=False),
    sa.Column('preferred_language', sa.String(length=5), server_default='he', nullable=False),
    sa.Column('calendar_refresh_token', sa.Text(), nullable=True),
    sa.Column('calendar_connected', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('calendar_connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('patients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('display_id', sa.Integer(), server_default=sa.text("nextval('patients_display_id_seq')"), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id_number', sa.String(length=500), nullable=True),
    sa.Column('id_number_hash', sa.String(length=64), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('phone', sa.String(length=500), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('blood_type', sa.String(length=10), nullable=True),
    sa.Column('allergies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('profession', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('insurance_info', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_display_id'), 'patients', ['display_id'], unique=True)
    op.create_index(op.f('ix_patients_id_number_hash'), 'patients', ['id_number_hash'], unique=True)
    op.create_index(op.f('ix_patients_name'), 'patients', ['name'], unique=False)
    op.create_table('question_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_shared', sa.Boolean(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_templates_user_id'), 'question_templates', ['user_id'], unique=False)
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='scheduled', nullable=False),
    sa.Column('reminder_minutes', sa.Integer(), nullable=False),
    sa.Column('google_event_id', sa.String(length=255), nullable=True),
    sa.Column('synced_to_google', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_appointments_start_time'), 'appointments', ['start_time'], unique=False)
    op.create_index(op.f('ix_appointments_user_id'), 'appointments', ['user_id'], unique=False)
    op.create_table('visits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('display_id', sa.Integer(), server_default=sa.text("nextval('visits_display_id_seq')"), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'in_progress', 'completed', 'cancelled', name='visitstatus'), nullable=False),
    sa.Column('source', sa.String(length=20), server_default='recording', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visits_display_id'), 'visits', ['display_id'], unique=True)
    op.create_index(op.f('ix_visits_doctor_id'), 'visits', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_visits_patient_id'), 'visits', ['patient_id'], unique=False)
    op.create_table('recordings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('visit_id', sa.UUID(), nullable=False),
    sa.Column('audio_url', sa.String(length=1000), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('encryption_key', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recordings_visit_id'), 'recordings', ['visit_id'], unique=False)
    op.create_table('summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('display_id', sa.Integer(), server_default=sa.text("nextval('summaries_display_id_seq')"), nullable=False),
    sa.Column('visit_id', sa.UUID(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('chief_complaint', sa.Text(), nullable=True),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('diagnosis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('treatment_plan', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('urgency', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=20), server_default='ai', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('questionnaire_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'done', 'error', name='summarystatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_summaries_display_id'), 'summaries', ['display_id'], unique=True)
    op.create_index(op.f('ix_summaries_visit_id'), 'summaries', ['visit_id'], unique=False)
    op.create_table('transcriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recording_id', sa.UUID(), nullable=False),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('speakers_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('wer_score', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'done', 'error', name='transcriptionstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcriptions_recording_id'), 'transcriptions', ['recording_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcriptions_recording_id'), table_name='transcriptions')
    op.drop_table('transcriptions')
    op.drop_index(op.f('ix_summaries_visit_id'), table_name='summaries')
    op.drop_index(op.f('ix_summaries_display_id'), table_name='summaries')
    op.drop_table('summaries')
    op.drop_index(op.f('ix_recordings_visit_id'), table_name='recordings')
    op.drop_table('recordings')
    op.drop_index(op.f('ix_visits_patient_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_doctor_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_display_id'), table_name='visits')
    op.drop_table('visits')
    op.drop_index(op.f('ix_appointments_user_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_start_time'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_question_templates_user_id'), table_name='question_templates')
    op.drop_table('question_templates')
    op.drop_index(op.f('ix_patients_name'), table_name='patients')
    op.drop_index(op.f('ix_patients_id_number_hash'), table_name='patients')
    op.drop_index(op.f('ix_patients_display_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tags_tag_type'), table_name='tags')
    op.drop_index(op.f('ix_tags_tag_code'), table_name='tags')
    op.drop_index(op.f('ix_tags_source'), table_name='tags')
    op.drop_index(op.f('ix_tags_entity_type'), table_name='tags')
    op.drop_index(op.f('ix_tags_entity_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_table('clinics')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.execute("DROP SEQUENCE IF EXISTS summaries_display_id_seq")
    op.execute("DROP SEQUENCE IF EXISTS visits_display_id_seq")
    op.execute("DROP SEQUENCE IF EXISTS patients_display_id_seq")
    # ### end Alembic commands ###
